import random

responses = {
    "hello": ["hi there", "hello how are you", "hi how can help you"],
    "how are you": ["I'm fine how can I help you?", "I don't have feelings, but thanks for asking"],
    "what is your name": ["I'm chatbot generated by Dipak", "My name is Dipak's AI chatbot version 0.1", "Myself Dipak's chatbot version 0.1"],
    "bye": ["Nice to meet you", "Will see you again", "See you", "Goodbye", "Bye"],
    "can you answer of any question": ["yes, i will try", "yes, you can ask any question","please ask your questions i will try my best"],
    "what is an ai": ["AI, which stands for Artificial Intelligence, refers to the simulation of human intelligence processes by computer systems"],
    "default": ["I'm Dipak's AI chatbot", "Please ask anything if you have doubts."]
}

# function to generate a response based on user input
def chatbot_response(user_input):
    # convert user input to lowercase for case-insensitive matching
    user_input = user_input.lower()

    # check if user input matches any predefined patterns
    for pattern, response_list in responses.items():
        if pattern in user_input:
            return random.choice(response_list)

    # if no match is found, use the default response
    return random.choice(responses["default"])

# main loop to run the chatbot
while True:
    user_input = input("you: ")
    if user_input.lower() == "exit":
        print("chatbot: Goodbye!")
        break
    response = chatbot_response(user_input)
    print("chatbot:", response)
